// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmvCdmWPyqvzMYBKQLqrvrhUzjHSjS3j8',
    appId: '1:318692928601:web:a1c929a77e75a617ae1548',
    messagingSenderId: '318692928601',
    projectId: 'student-central-3161f',
    authDomain: 'student-central-3161f.firebaseapp.com',
    storageBucket: 'student-central-3161f.appspot.com',
    measurementId: 'G-19X3S46FDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyb4kCA9taK-fEguzk03O7rnQgxEdjanY',
    appId: '1:318692928601:android:9aa80408f2a4c2f0ae1548',
    messagingSenderId: '318692928601',
    projectId: 'student-central-3161f',
    storageBucket: 'student-central-3161f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbycI8TXhD5phNz3Xes7ncyUFvr8chFqg',
    appId: '1:318692928601:ios:c2d2c8c7f5a8d06bae1548',
    messagingSenderId: '318692928601',
    projectId: 'student-central-3161f',
    storageBucket: 'student-central-3161f.appspot.com',
    iosBundleId: 'com.studentcentral.kquizon.studentCentral',
  );
}
